default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  min_messages: WARNING

development:
  <<: *default
  database: personalsam_development

production:
  <<: *default
  database: personalsam_development

test:
  <<: *default
  database: personalsam_test
