# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdf03ee3ed8a0e3ddfd94ad1aebaad7dd6a6c747ae3cc8cc0917421e2f4e2dc7adc850a6b2c37afb6f32d03c83af45751c4f897a80760f0f19d7376bae1fc372

test:
  secret_key_base: 0ef8af5b93ec221708243338e424e1a6ded592ad9c99daa75fd794c1a0012d1f62566738909e8492e61829b0b370dcf0212cc3b5b831f46a2c6e48bf465f2b1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
